// client/components/GNB.vue
<template>
  <div class="nav-container">
    <nav>
      <div class="side-block">
        <nuxt-link to="/" id="logo-btn">
          <img src="/logo/main.png" alt="블라인드 로고" width="150" />
        </nuxt-link>
        <nuxt-link to="/" :class="['text-menu', $route.name === 'index' && 'active']">홈</nuxt-link>
        <nuxt-link to="/write" :class="['text-menu', $route.name === 'write' && 'active']">글쓰기</nuxt-link>
      </div>
      <div class="side-block">
        <!-- <SmallSearchbar /> -->
        <button @click.prevent="clickWritingButton"  class="hover:bg-light-blue-200 hover:text-light-blue-800 group flex items-center rounded-md bg-light-blue-100 text-light-blue-600 text-sm font-medium px-4 py-2">
          <svg class="group-hover:text-light-blue-600 text-light-blue-500 mr-2" width="12" height="20" fill="currentColor">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M6 5a1 1 0 011 1v3h3a1 1 0 110 2H7v3a1 1 0 11-2 0v-3H2a1 1 0 110-2h3V6a1 1 0 011-1z"/>
          </svg>
          글쓰기
        </button>

        <button @click.prevent="clickLoginButton"  class="hover:bg-light-blue-200 hover:text-light-blue-800 group flex items-center rounded-md bg-light-blue-100 text-light-blue-600 text-sm font-medium px-4 py-2">
          <svg class="group-hover:text-light-blue-600 text-light-blue-500 mr-2" width="18" height="20" fill="currentColor">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
          </svg>
          {{!user.email   ? "로그인": "로그아웃"}}
        </button>

        
      </div>
      <LoginModal />
      <WritingModal />
    </nav>
  </div>
</template>
<script>
import SmallSearchbar from "@/components/GNB/SmallSearchbar";
import LoginModal from "@/components/Modal/LoginAndRegister";
import WritingModal from "@/components/Modal/Writing";
import { mapState } from "vuex";
export default {
  components: {
    SmallSearchbar,
    LoginModal,
    WritingModal,
  },
  computed: {
    ...mapState(["user","modal"])
  },
  methods: {
    clickWritingButton() {
      if (!this.user.email) {
        this.$store.commit("modal/SET_LOGIN_MODAL_OPEN");
        return;
      }
      this.$store.commit("modal/SET_WRITING_MODAL_STATE", true);
    },
    clickLoginButton() {
      if (!this.user.email) {
        this.$store.commit("modal/SET_LOGIN_MODAL_OPEN");
        return;
      }
      this.logout();
    },
    logout() {
      this.$store.commit("user/SET_USER", {
        email: null,
        nickname: null
      });

      alert("로그아웃.!")
    }
  }
};
</script>
<style lang="scss" scoped>
.nav-container {
  border-bottom: 1px solid #d4d4d4;
}
nav {
  display: flex;
  justify-content: space-between;
  align-items: center;
  width: 100%;
  height: 80px;
  margin: auto;
  padding: 0 20px;
  max-width: 1100px;
  .side-block {
    display: flex;
    height: 100%;
    align-items: center;
    #logo-btn {
      margin-right: 60px;
    }
    .text-menu {
      color: #222;
      font-size: 20px;
      margin-right: 30px;
    }
    
  }
}
</style>

// react-client/src/components/Gnb.js
import { Link } from "react-router-dom";
import styles from "../assets/gnb.scss";
import { useSelector, useDispatch, shallowEqual } from "react-redux";
import { setLoginModalOpen } from "../store/modal";
import { setUser } from "../store/user";

import LoginAndRegister from "../components/Modal/LoginAndRegister";

const Gnb = () => {
  const { user, modal } = useSelector(
    (state) => ({
      user: state.user,
      modal: state.modal,
    }),
    shallowEqual
  );

  let showAuthMenu = false;

  if (user.authYn === "Y") {
    showAuthMenu = true;
  }

  const dispatch = useDispatch();

  const onClickLoginButton = () => {
    if (!user.email) {
      dispatch(setLoginModalOpen());
      return;
    }

    logout();
  };

  const logout = () => {
    let user = {
      email: null,
      nickname: null,
      authYn: null,
    };

    dispatch(setUser(user));
    alert("로그아웃");
  };

  return (
    <div className={styles.navContainer}>
      <nav>
        <div className="flex h-full items-center ">
          <Link to="/">
            <img
              src={require("../static/logo/main.png")}
              alt="블라인드 로고"
              width="150"
            />
          </Link>
        </div>

        <div className="flex h-full items-center">
          {showAuthMenu ? (
            <Link to="/admin">
              <button className="hover:bg-light-blue-200 hover:text-light-blue-800 group flex items-center rounded-md bg-light-blue-100 text-light-blue-600 text-sm font-medium px-2 py-2">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-6 w-6"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"
                  />
                </svg>
                관리자
              </button>
            </Link>
          ) : null}

          <Link to="/write">
            <button className="hover:bg-light-blue-200 hover:text-light-blue-800 group flex items-center rounded-md bg-light-blue-100 text-light-blue-600 text-sm font-medium px-2  py-2">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                />
              </svg>
              글쓰기
            </button>
          </Link>

          {/* <Button
            onClickFn={onClickLoginButton}
            title={!user.email ? "로그인" : "로그아웃"}
            color={"blue"}
          /> */}
          <button
            onClick={onClickLoginButton}
            className="hover:bg-light-blue-200 hover:text-light-blue-800 group flex items-center rounded-md bg-light-blue-100 text-light-blue-600 text-sm font-medium px-2 py-2"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-6 w-6"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
            {!user.email ? "로그인" : "로그아웃"}
          </button>

          <LoginAndRegister modal={modal} />
        </div>
      </nav>
    </div>
  );
};

export default Gnb;
