// react-client/src/components/Home.js
import React from "react";
import axios from "../api";
import { useEffect, useState } from "react";

function Home() {
  const [boardList, setBoardList] = useState([]);
  console.log(boardList);

  const fetchHotels = async () => {
    try {
      // 요청 처음에 초기화
      setBoardList([]);

      const data = await axios({
        url: "/main",
        method: "get",
      });

      console.log(data.content[0].content);

      setBoardList(data);
    } catch (e) {
      console.err(e);
    }
  };

  useEffect(() => {
    fetchHotels();
  }, []);

  return (
    <div>
      <div className="container mx-auto my-4 max-w-screen-xl">
        <img
          src={require("../static/main/okinawa.png")}
          alt=""
          className="mx-auto justify-center items-end pb-4 flex rounded-3xl "
        />
      </div>
      <div>
        {/* {boardList.map(
          (board) => console.log(board)
          // <div>{board.title}</div>
        )} */}
      </div>
    </div>
  );
}

export default Home;

// client/src/components/Home.vue
<template>
  <div>
    <div class="container mx-auto px-44 my-4 ">
      <img src="@/static/main/okinawa.png" alt=""  class="mx-auto justify-center items-end pb-4 flex rounded-3xl ">
    </div>

    <div class="main-container">

    </div>

  </div>
</template>
<script>

export default {
  components: {
  },
  data() {
    return {
      mainContent: [],
    };
  },
  created() {
    this.getRecentBoardArticleList();
  },
  methods: {
    async getRecentBoardArticleList() {
      // const data = await this.$api.$get("/main");
      const data = await this.$api({
        url : '/main',
        method: 'get'
      });

      if (data.error) {
        return;
      }

      if(!data.content){
        return;
      }

      this.mainContent = data.content;
    }
  }
};
</script>
<style lang="scss">
.main-container {
  display: flex;
  margin: auto;
  width: 100%;
  justify-content : space-between;;
  max-width: 1100px;
  main {
    width: 100%;
    max-width: 736px;
  }
}
.board-card-container {
  width: 100%;
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-gap: 45px 40px;
}
</style>
